export const DAILY_LEADS_OVERVIEW_HEADERS = [
  { label: "DATE", key: "date", align: "left" },
  { label: "DAYS", key: "days", align: "left" },
  { label: "FB", key: "fb", align: "center" },
  { label: "WB", key: "wb", align: "center" },
  { label: "COMPANY", key: "company", align: "center" },
  { label: "GST", key: "gst", align: "center" },
  { label: "GOOGLE", key: "google", align: "center" },
  { label: "IM", key: "im", align: "center" },
  { label: "JD", key: "jd", align: "center" },
  { label: "REF", key: "ref", align: "center" },
  { label: "EMAIL", key: "email", align: "center" },
  { label: "OTHERS", key: "others", align: "center" },
  { label: "LEAD GENERATED", key: "leadGenerated", align: "center" },
  { label: "LEAD CLOSED", key: "leadClosed", align: "center" },
  { label: "DOM.PAYMENT", key: "domPayment", align: "right" },
  { label: "INT PAYMENT", key: "intPayment", align: "right" },
];

export const DAILY_LEADS_OVERVIEW_BODY = [
  {
    date: "17/02/25",
    days: "Monday",
    fb: 40,
    wb: 24,
    company: 13,
    gst: 18,
    google: 1,
    im: 1,
    jd: 1,
    ref: 1,
    email: 1,
    others: 1,
    leadGenerated: 1,
    leadClosed: 1,
    domPayment: 1,
    intPayment: 1,
  },
  {
    date: "16/02/25",
    days: "Sunday",
    fb: 35,
    wb: 20,
    company: 15,
    gst: 12,
    google: 1,
    im: 1,
    jd: 1,
    ref: 1,
    email: 1,
    others: 1,
    leadGenerated: 1,
    leadClosed: 1,
    domPayment: 1,
    intPayment: 1,
  },
  {
    date: "15/02/25",
    days: "Saturday",
    fb: 45,
    wb: 28,
    company: 10,
    gst: 15,
    google: 1,
    im: 1,
    jd: 1,
    ref: 1,
    email: 1,
    others: 1,
    leadGenerated: 1,
    leadClosed: 1,
    domPayment: 1,
    intPayment: 1,
  },
];

export const LeadstableHeading = [
  { label: "receivedDate", align: "left" },
  { label: "name", align: "left" },
  { label: "number", align: "left" },
  { label: "company", align: "left" },
  { label: "email", align: "left" },
  { label: "address", align: "left" },
  { label: "agent", align: "left" },
  { label: "status", align: "center" },
  { label: "source", align: "left" },
  { label: "quotation", align: "left" },
  { label: "notes", align: "left" },
  { label: "reminder", align: "left" },
  // { label: "lastCall", align: "left" },
  // { label: "actions", align: "center" },
];

export const LeadstableData = [
  {
    date: "27 Mar, 2024",
    name: "Avi",
    phoneNumber: "1982748924",
    company: "13",
    email: "example@gmail.com",
    location: "1",
    agent: "Rocky",
    status: "Open",
    // actions: "Assign",
  },
  {
    date: "27 Mar, 2024",
    name: "Avi",
    phoneNumber: "1982748924",
    company: "13",
    email: "example@gmail.com",
    location: "1",
    agent: "Rocky",
    status: "Closed",
    // actions: "Assign",
  },
  {
    date: "27 Mar, 2024",
    name: "Avi",
    phoneNumber: "1982748924",
    company: "13",
    email: "example@gmail.com",
    location: "1",
    agent: "Rocky",
    status: "Closed",
    // actions: "Assign",
  },
];

export const AgenttableHeading = [
  { label: "Sr no.", align: "left" },
  { label: "name", align: "left" },
  { label: "phoneNumber", align: "left" },

  { label: "email", align: "left" },

  // { label: "assignedLeads", align: "center" },
  { label: "actions", align: "center" },
];

export const AgenttableData = [
  {
    name: "Avi",
    phoneNumber: "1982748924",

    email: "ASDF@asdf.xom",
    "cancelled leads": "13",
    // actions: "Assign",
  },
  {
    name: "Avi",
    phoneNumber: "1982748924",

    email: "ASDF@asdf.xom",
    "cancelled leads": "13",
    // actions: "Assign",
  },
  {
    name: "Avi",
    phoneNumber: "1982748924",

    email: "ASDF@asdf.xom",
    "cancelled leads": "13",
    // actions: "Assign",
  },
  {
    name: "Avi",
    phoneNumber: "1982748924",

    email: "ASDF@asdf.xom",
    "cancelled leads": "13",
    // actions: "Assign",
  },
];

// export const LEAD_STATUS = [
//   "Unassigned",
//   "Not Contacted",
//   "Contacted",
//   "Quotation Sent",
//   "Payment Link sent",
//   "Documents Received",
//   "Payment Received",
//   "Completed",
//   "Rejected",
//   ,
//   "Hang up",
// ];
export const LEAD_STATUS = [
  "Unassigned",
  "Not Contacted", //
  "Contacted",
  "Not Answering",
  "Busy",
  "Hang up",
  "Wrong Number",
  "Not Reachable",
  "Not Contactable",
  "Switch Off", // or Switch Off
  "Call Back",
  "Call Back Later",
  "Follow Up",
  "Follow-up Required",
  "Meeting Scheduled",
  "Profile Shared",
  "Quotation Sent",
  "Quotation Shared",
  "Payment Link Sent",
  // "Payment Link sent", // consider unifying the casing
  "Document Received",
  // "Documents Received", // consider unifying with "Document Received"
  "Payment Received",
  "Transferred to Sales/Support",
  "Deal Closed",
  "Completed",
  "Feedback Taken",
  "Reminder Set",
  "Not Interested",
  "Rejected",
  "Already Taken from others",
  "No Further Required",
  "Technical Error",
  "Others",
  "Withdraw",
];
export const statusColorMap = {
  Unassigned: "bg-gray-400",
  "Not Contacted": "bg-yellow-500",
  Contacted: "bg-green-500",
  "Not Answering": "bg-red-400",
  Busy: "bg-orange-400",
  "Hang up": "bg-red-800",
  "Wrong Number": "bg-red-600",
  "Not Reachable": "bg-red-500",
  "Not Contactable": "bg-cyan-800",
  "Switched Off": "bg-red-700",
  "Call Back": "bg-lime-400",
  "Call Back Later": "bg-lime-400",
  "Follow Up": "bg-fuchsia-500",
  "Follow-up Required": "bg-fuchsia-500",
  "Meeting Scheduled": "bg-emerald-500",
  "Profile Shared": "bg-sky-500",
  "Quotation Sent": "bg-blue-500",
  "Quotation Shared": "bg-blue-400",
  "Payment Link Sent": "bg-indigo-500",
  // "Payment Link sent": "bg-indigo-500",
  "Document Received": "bg-blue-300",
  // "Documents Received": "bg-blue-300",
  "Payment Received": "bg-green-600",
  "Transferred to Sales/Support": "bg-pink-600",
  "Deal Closed": "bg-green-700",
  Completed: "bg-green-800",
  "Feedback Taken": "bg-purple-400",
  "Reminder Set": "bg-purple-500",
  "Not Interested": "bg-orange-500",
  Rejected: "bg-orange-600",
  "Already Taken from others": "bg-yellow-600",
  "No Further Required": "bg-gray-500",
  "Technical Error": "bg-red-900",
  Others: "bg-black",
  Withdraw: "bg-red-600",
};

export const MARKETING_TABLE_HEADERS = [
  { label: "Name", key: "name", align: "left" },
  { label: "Email", key: "email", align: "left" },
  { label: "Phone Number", key: "number", align: "left" },
  { label: "Source", key: "source", align: "left" },
];

export const PAYMENT_LINK_TABLE_HEADERS = [
  // { label: "date", align: "left" },
  { label: "agent", align: "left" },
  { label: "today", align: "left" },
  { label: "month", align: "left" },
  { label: "count", align: "left" },

  // { label: "status", align: "left" },
  // { label: "expiry", align: "left" },
  // { label: "notes", align: "left" },
  { label: "actions", align: "center" },
];

export const PAYMENT_HISTORY_TABLE_HEADERS = [
  // { label: "date", align: "left" },
  { label: "agent", align: "left" },
  { label: "msr", align: "left" },
  { label: "qcci", align: "left" },
  { label: "qcci fb lead", align: "left" },
  { label: "msr fb lead", align: "left" },

  { label: "insta", align: "left" },
  { label: "company data", align: "left" },
  { label: "just dail", align: "left" },
  { label: "indiamart", align: "left" },
  { label: "google ads", align: "left" },
  { label: "consultant", align: "left" },
  { label: "gst", align: "left" },
  { label: "govt fees", align: "left" },
  { label: "body", align: "left" },
  { label: "total prof fees", align: "left" },
  { label: "gross total", align: "left" },

  // { label: "today", align: "left" },
  // { label: "month", align: "left" },
  // { label: "count", align: "left" },

  // { label: "status", align: "left" },
  // { label: "expiry", align: "left" },
  // { label: "notes", align: "left" },
  // { label: "actions", align: "center" },
];
export const PAYMENT_HISTORY_TOTAL_TABLE_HEADERS = [
  // { label: "date", align: "left" },
  { label: "agent", align: "left" },
  // { label: "msr", align: "left" },
  // { label: "qcci", align: "left" },
  // { label: "qcci fb lead", align: "left" },
  // { label: "msr fb lead", align: "left" },

  // { label: "insta", align: "left" },
  // { label: "company data", align: "left" },
  // { label: "just dail", align: "left" },
  // { label: "indiamart", align: "left" },
  // { label: "google ads", align: "left" },
  // { label: "consultant", align: "left" },
  // { label: "gst", align: "left" },
  // { label: "govt fees", align: "left" },
  // { label: "body", align: "left" },
  // { label: "total prof fees", align: "left" },
  // { label: "gross total", align: "left" },

  { label: "today", align: "left" },
  { label: "month", align: "left" },
  { label: "count", align: "left" },

  // { label: "status", align: "left" },
  // { label: "expiry", align: "left" },
  // { label: "notes", align: "left" },
  // { label: "actions", align: "center" },
];

export const AGENT_IDLE_TIME = [
  { label: "Agent", key: "agent", align: "left" },
  { label: "Login Time", key: "loginTime", align: "left" },
  { label: "Break Time", key: "breakTime", align: "left" },
  { label: "Total Call Time", key: "callTime", align: "left" },
  { label: "Logout Time", key: "logoutTime", align: "left" },
  { label: "Idle Time", key: "idleTime", align: "left" },
];

export const PRIMARY = "#3796CF";
export const SECONDARY = "#FFA112";

export const AccountDetails = {
  "GST Account Domestic/International USD":
    "MSR ASSESSMENT PRIVATE LIMITED\nA/c - 50200073444028\nIFSC - HDFC0000693\nBranch - Park Street\nBank Name - HDFC Bank\nswift code: HDFCINBBCAL\nUPI Id : msrassessment-1@okhdfcbank\nGpay / Phonepe : 8337004170",
  "Non-GST Account Domestic":
    "MSR ASSESSMENT PRIVATE LIMITED\nA/c - 921020030213726\nIFSC - UTIB0004704\nBranch - Elliot Road Kolkata\nBank Name - Axis Bank Ltd\nUPI Id: msrassessment@oksbi\nPhonepe/Gpay- 8337004170",
  "QCCI LLP":
    "ACCOUNT NO : 10062914746\nIFSC CODE : IDFB0040133\nIDFC FIRST BANK\nPHONEPE / GPAY : 9051786886",
};
export const quotationServices = [
  {
    service: "CHECKLIST FOR 12A & 80G",
    soleOptions: [
      "COPY OF PAN CARD OF ENTITY.",
      "NOTES ON THE ACTIVITIES OF THE TRUST OR INSTITUTION.",
      "SELF-CERTIFIED COPY OF THE DOCUMENTS SHOWING/EVIDENCING MODIFICATION OR ADOPTION OF THE OBJECTS",
      "THE DETAILS OF THE DARPAN REGISTRATION, IF THE ORGANISATION IS REGISTERED ON THE DARPAN PORTAL (IF ANY)",
      "SELF-CERTIFIED COPY OF THE INCORPORATION DOCUMENT OF SOCIETIES/TRUST/NGO/SECTION-8 COMPANY.",
      "COPY OF TRUST DEED/SOCIETY DEED/NOG BY LAWS/ MOA& AOA OF SECTION-8 COMPANY (ANY ONE AS THE CASE MAY BE)",
      "SELF-CERTIFIED COPY OF THE EXISTING ORDER OF REGISTRATION UNDER SECTION 12A/12AA/12AB, AS THE CASE MAY BE (IF ANY)",
      "SELF-CERTIFIED COPY OF THE REGISTRATION WITH THE REGISTRAR OF COMPANIES OR REGISTRAR OF SOCIETIES OR REGISTRAR OF FIRMS OR REGISTRAR OF PUBLIC TRUSTS, AS THE CASE MAY BE",
      "SELF-CERTIFIED COPY OF REGISTRATION UNDER THE FCRA [FOREIGN CONTRIBUTION (REGULATION) ACT], 2010, IF THE APPLICANT IS REGISTERED UNDER THE RESPECTIVE ACT. (IF ANY)",
      "COPIES OF THE ANNUAL ACCOUNTS FOR A PERIOD NOT EXCEEDING THREE YEARS IMMEDIATELY PRIOR TO THE YEAR IN WHICH THE APPLICATION IS MADE, IN THE CASE OF EXISTING ENTITIES",
      "WHERE THE INCOME OF THE ORGANISATION INCLUDES THE PROFITS AND GAINS OF BUSINESS OR WHERE A BUSINESS UNDERTAKING IS HELD BY THE ORGANISATION UNDER THE PROVISIONS OF SECTION 11(4A), COPIES OF THE ANNUAL ACCOUNTS AND AUDIT REPORT UNDER SECTION 44AB FOR THREE YEARS IMMEDIATELY PRIOR TO THE YEAR IN WHICH THE APPLICATION IS MADE",
    ],
    pvtOptions: [
      "COPY OF PAN CARD OF ENTITY.",
      "NOTES ON THE ACTIVITIES OF THE TRUST OR INSTITUTION.",
      "SELF-CERTIFIED COPY OF THE DOCUMENTS SHOWING/EVIDENCING MODIFICATION OR ADOPTION OF THE OBJECTS",
      "THE DETAILS OF THE DARPAN REGISTRATION, IF THE ORGANISATION IS REGISTERED ON THE DARPAN PORTAL (IF ANY)",
      "SELF-CERTIFIED COPY OF THE INCORPORATION DOCUMENT OF SOCIETIES/TRUST/NGO/SECTION-8 COMPANY.",
      "COPY OF TRUST DEED/SOCIETY DEED/NOG BY LAWS/ MOA& AOA OF SECTION-8 COMPANY (ANY ONE AS THE CASE MAY BE)",
      "SELF-CERTIFIED COPY OF THE EXISTING ORDER OF REGISTRATION UNDER SECTION 12A/12AA/12AB, AS THE CASE MAY BE (IF ANY)",
      "SELF-CERTIFIED COPY OF THE REGISTRATION WITH THE REGISTRAR OF COMPANIES OR REGISTRAR OF SOCIETIES OR REGISTRAR OF FIRMS OR REGISTRAR OF PUBLIC TRUSTS, AS THE CASE MAY BE",
      "SELF-CERTIFIED COPY OF REGISTRATION UNDER THE FCRA [FOREIGN CONTRIBUTION (REGULATION) ACT], 2010, IF THE APPLICANT IS REGISTERED UNDER THE RESPECTIVE ACT. (IF ANY)",
      "COPIES OF THE ANNUAL ACCOUNTS FOR A PERIOD NOT EXCEEDING THREE YEARS IMMEDIATELY PRIOR TO THE YEAR IN WHICH THE APPLICATION IS MADE, IN THE CASE OF EXISTING ENTITIES",
      "WHERE THE INCOME OF THE ORGANISATION INCLUDES THE PROFITS AND GAINS OF BUSINESS OR WHERE A BUSINESS UNDERTAKING IS HELD BY THE ORGANISATION UNDER THE PROVISIONS OF SECTION 11(4A), COPIES OF THE ANNUAL ACCOUNTS AND AUDIT REPORT UNDER SECTION 44AB FOR THREE YEARS IMMEDIATELY PRIOR TO THE YEAR IN WHICH THE APPLICATION IS MADE",
    ],
  },
  {
    service: "CHECKLIST FOR APEDA",
    soleOptions: [
      "PAN CARD",
      "AADHAR CARD",
      "PHONE NUMBER AND EMAIL ID",
      "LEGAL DOCUMENTS (MSME/GST/TRADE LICENSE)",
      "BANK ACCOUNT STATEMENT/CANCEL CHEQUE IN THE NAME OF THE ORGANIZATION",
      "APPLICATION FORM FOR THE APEDA REGISTRATION THAT IS COMPLETED AND DULY SIGNED.",
      "COPY OF THE IMPORT-EXPORT CODE ISSUED BY THE DIRECTORATE GENERAL OF FOREIGN TRADE.",
      "BANK CERTIFICATE THAT IS DULY SIGNED BY THE CONCERNED AUTHORITIES.",
    ],
    pvtOptions: [
      "PAN CARD OF BUSINESS ENTITY.",
      "CERTIFICATE OF INCORPORATION",
      "PHONE NUMBER AND EMAIL ID",
      "AOA AND MOA IN THE CASE OF COMPANY OR LLP AGREEMENT IN THE CASE OF LLP OR PARTNERSHIP DEED IN THE CASE OF PARTNERSHIP FIRM.",
      "BANK ACCOUNT STATEMENT/CANCEL CHEQUE IN THE NAME OF THE ORGANIZATION",
      "LIST OF PARTNERS OR DIRECTORS AADHAR CARD, PAN CARD & NUMBER",
      "APPLICATION FORM FOR THE APEDA REGISTRATION THAT IS COMPLETED AND DULY SIGNED.",
      "COPY OF THE IMPORT-EXPORT CODE ISSUED BY THE DIRECTORATE GENERAL OF FOREIGN TRADE.",
      "BANK CERTIFICATE THAT IS DULY SIGNED BY THE CONCERNED AUTHORITIES.",
    ],
    isMultipleEntity: true,
  },
  {
    service: "CHECKLIST FOR DESIGN REGISTRATION",
    soleOptions: [
      "BUSINESS NAME",
      "NATURE OF BUSINESS",
      "PROPRIETOR'S PAN CARD",
      "PROPRIETOR'S AADHAAR CARD",
      "BUSINESS COMMENCEMENT DATE",
      "BUSINESS E-MAIL ID & BUSINESS MOBILE NUMBER",
    ],
    pvtOptions: [
      "CIN NUMBER",
      "BUSINESS NAME",
      "BUSINESS ADDRESS",
      "NATURE OF BUSINESS",
      "COMPANY PAN CARD",
      "DIRECTOR’S AADHAAR CARD",
      "BUSINESS E-MAIL ID & MOBILE NUMBER",
    ],
    isMultipleEntity: true,
  },
  {
    service: "CHECKLIST FOR DRUG LICENSE – RETAIL",
    soleOptions: [
      "APPLICANT’S IDENTITY PROOF",
      "APPLICANT’S ADDRESS PROOF",
      "AFFIDAVIT OF THE APPLICANT",
      "TRADE LICENSE OF ORGANIZATION.",
      "PHARMACIST AND APPOINTMENT LETTER.",
      "BUSINESS CONSTITUTION DOCUMENTS.",
      "PASSPORT SIZE PHOTOGRAPH OF THE OWNERS.",
      "INVOICE OF REFRIGERATOR IN THE NAME BUSINESS.",
      "SELF -ATTESTED COPY OF THE SKETCH MAP OF PREMISES (PREPARED IN AUTOCAD)",
      "IN CASE OF OWNED PROPERTY, COPY OF THE UTILITY BILL AND PROPERTY TAX RECEIPT.",
      "EDUCATIONAL QUALIFICATION ALONG WITH EXPERIENCE LETTER OF THE REGISTERED",
      "IN CASE OF RENTED PREMISE, NOTARISED RENT AGREEMENT WITH RENT RECEIPT.",
      "INCLUDING NOC (NO- OBJECTION CERTIFICATE) FROM THE LANDLORD.",
      "DOCUMENTS RELATED TO REGISTERED PHARMACIST:",
      "ORIGINAL AFFIDAVIT OF PHARMACIST",
      "RECORD FORM OF THE PHARMACIST",
      "SCANNED SIGNATURE OF THE APPLICANT",
      "AFFIDAVIT FROM REGISTERED PHARMACIST",
      "COPY OF APPOINTMENT AND JOINING LETTER",
      "COPY OF RENEWAL OF REGISTRATION (IF APPLICABLE)",
      "2 PASSPORT SIZE PHOTOGRAPHS PER APPLIED LICENSE",
      "COPY OF REGISTRATION CERTIFICATE FROM PHARMACY COUNCIL",
    ],
    pvtOptions: [
      "DIRECTO’S IDENTITY PROOF",
      "DIRECTO’S ADDRESS PROOF",
      "AFFIDAVIT OF THE APPLICANT",
      "TRADE LICENSE OF ORGANIZATION.",
      "BILL AND PROPERTY TAX RECEIPT.",
      "PHARMACIST AND APPOINTMENT LETTER.",
      "PASSPORT SIZE PHOTOGRAPH OF THE DIRECTO’S.",
      "INVOICE OF REFRIGERATOR IN THE NAME BUSINESS.",
      "INCLUDING NOC (NO- OBJECTION CERTIFICATE) FROM THE LANDLORD.",
      "BUSINESS CONSTITUTION DOCUMENTS (COI, PARTNERSHIP DEED, ETC.)",
      "SELF -ATTESTED COPY OF THE SKETCH MAP OF PREMISES (PREPARED IN AUTOCAD)",
      "EDUCATIONAL QUALIFICATION ALONG WITH EXPERIENCE LETTER OF THE REGISTER",
      "IN CASE OF RENTED PREMISE, NOTARISED RENT AGREEMENT WITH RENT RECEIPT.",
      "DOCUMENTS RELATED TO REGISTERED PHARMACIST:",
      "ORIGINAL AFFIDAVIT OF PHARMACIST",
      "RECORD FORM OF THE PHARMACIST",
      "SCANNED SIGNATURE OF THE DIRECTO’S",
      "AFFIDAVIT FROM REGISTERED PHARMACIST",
      "COPY OF APPOINTMENT AND JOINING LETTER",
      "COPY OF RENEWAL OF REGISTRATION (IF APPLICABLE)",
      "2 PASSPORT SIZE PHOTOGRAPHS PER APPLIED LICENSE",
      "COPY OF REGISTRATION CERTIFICATE FROM PHARMACY COUNCIL",
    ],
    isMultipleEntity: true,
  },
  {
    service: "CHECKLIST FOR DRUG LICENSE – WHOLESALE",
    soleOptions: [
      "TRADE LICENSE",
      "AFFIDAVIT BY OWNER",
      "COMPETENT PERSON",
      "PROPERTY TAX RECEIPT",
      "OWNER’S IDENTITY PROOF",
      "OWNER’S ADDRESS PROOF",
      "AADHAR & PAN CARD OF COMPETENT PERSON",
      "AFFIDAVIT BY THE COMPETENT PERSON",
      "SCANNED COPY OF SIGNATURE OF OWNER",
      "PASSPORT SIZE PHOTOGRAPH OF THE OWNERS.",
      "RENT AGREEMENT & RENT RECEIPT, IF RENTED",
      "APPOINTMENT LETTER OF THE COMPETENT PERSON",
      "NOC (NO- OBJECTION CERTIFICATE) FROM THE LANDLORD",
      "INVOICE OF REFRIGERATOR USED FOR BUSINESS PURPOSE",
      "SELF -ATTESTED COPY OF THE SKETCH MAP OF PREMISES (PREPARED IN AUTOCAD)",
      "EDUCATIONAL QUALIFICATION ALONG WITH EXPERIENCE LETTER OF EDUCATIONAL QUALIFICATION OF OWNER",
    ],
    pvtOptions: [
      "TRADE LICENSE",
      "AFFIDAVIT BY OWNER",
      "COMPETENT PERSON",
      "PROPERTY TAX RECEIPT",
      "OWNER’S IDENTITY PROOF",
      "OWNER’S ADDRESS PROOF",
      "AADHAR & PAN CARD OF COMPETENT PERSON",
      "AFFIDAVIT BY THE COMPETENT PERSON",
      "SCANNED COPY OF SIGNATURE OF OWNER",
      "PASSPORT SIZE PHOTOGRAPH OF THE OWNERS.",
      "CERTIFICATE OF INCORPORATION, MOA & AOA",
      "RENT AGREEMENT & RENT RECEIPT, IF RENTED",
      "APPOINTMENT LETTER OF THE COMPETENT PERSON",
      "NOC (NO- OBJECTION CERTIFICATE) FROM THE LANDLORD",
      "INVOICE OF REFRIGERATOR USED FOR BUSINESS PURPOSE",
      "SELF -ATTESTED COPY OF THE SKETCH MAP OF PREMISES (PREPARED IN AUTOCAD)",
      "EDUCATIONAL QUALIFICATION ALONG WITH EXPERIENCE LETTER OF EDUCATIONAL QUALIFICATION OF OWNER",
    ],
    isMultipleEntity: true,
  },
  {
    service: "CHECKLIST FOR FSSAI BASIC",
    soleOptions: [
      "EMAIL ID",
      "PHONE NUMBER",
      "PHOTO ID PROOF",
      "LIST OF FOOD ITEMS LIST",
      "BUSINESS LEGAL DOCUMENTS",
      "PASSPORT SIZED PHOTOGRAPH",
      "PROOF OF BUSINESS PREMISES- OWNERSHIP (DOCUMENT/ELECTRICITY BILL/RENT AGREEMENT)",
    ],
    pvtOptions: [
      "EMAIL ID",
      "PHONE NUMBER",
      "PHOTO ID PROOF",
      "PARTNERSHIP DEED",
      "DIRECTORS ID PROOF",
      "LIST OF FOOD ITEMS LIST",
      "PASSPORT SIZED PHOTOGRAPH",
      "PROOF OF BUSINESS PREMISES- OWNERSHIP (DOCUMENT/ELECTRICITY BILL/RENT AGREEMENT)",
    ],
    isMultipleEntity: true,
  },
  {
    service: "CHECKLIST FOR FSSAI STATE",
    soleOptions: [
      "IMPORT EXPORT CERTIFICATE (IEC CODE)",
      "PHOTOGRAPHS OF THE UNIT IN SOFT COPY.",
      "LAYOUT / BLUEPRINT OF THE UNIT (IF MANUFACTURER)",
      "LIST OF LABORATORY EQUIPMENT (IF MANUFACTURER)",
      "BLANK LETTERHEAD FOR FSSAI DOCUMENT PREPARATION",
      "PROOF OF BUSINESS PREMISES - BILL/RENT AGREEMENT)",
      "OWNERSHIP (DOCUMENT/ELECTRICITY -",
      "LIST OF PLANT & MACHINERY WITH HORSE POWER AND NO. OF MACHINES (IF MANUFACTURER)",
    ],
    pvtOptions: [
      "LIST OF FOOD ITEMS LIST",
      "IMPORT EXPORT CERTIFICATE (IEC CODE)",
      "PARTNERSHIP DEED - IN CIN/MOA - COMPANY PAN CARD.",
      "PHOTO ID PROOF (WITH ADDRESS) OF (PARTNERS/DIRECTORS).",
      "PHOTOGRAPHS OF UNIT IN SOFT COPY.",
      "BLANK LETTERHEAD BLANK LETTERHEAD FOR FSSAI DOCUMENT PREPARATION",
      "GROUND PLAN OF THE UNIT (IF MANUFACTURER)",
      "PROOF OF BUSINESS PREMISES - OWNERSHIP (DOCUMENT/ELECTRICITY BILL/RENT AGREEMENT)",
      "LIST OF PLANT & MACHINERY - WITH HORSE POWER AND NO. OF MACHINES (IF MANUFACTURER)",
      "LIST OF LABORATORY EQUIPMENT (IF MANUFACTURER)",
    ],
    isMultipleEntity: true,
  },
  {
    service: "CHECKLIST FOR FSSAI CENTRAL",
    soleOptions: [
      "PHOTO ID PROOF",
      "LIST OF FOOD ITEMS LIST",
      "BUSINESS LEGAL DOCUMENTS",
      "PASSPORT SIZED PHOTOGRAPHS",
      "IMPORT EXPORT CERTIFICATE (IEC CODE)",
      "PHOTOGRAPHS OF UNIT IN SOFT COPY.",
      "GROUND PLAN OF THE UNIT (IF MANUFACTURER)",
      "LIST OF LABORATORY EQUIPMENT (IF MANUFACTURER)",
      "BLANK LETTERHEADS-25 NOS. (WITH SIGN & STAMP & A4 SIZE)",
      "PROOF OF BUSINESS PREMISES- OWNERSHIP (DOCUMENT/ELECTRICITY BILL/RENT AGREEMENT)",
      "LIST OF PLANT & MACHINERY-WITH HORSE POWER AND NO. OF MACHINES (IF MANUFACTURER)",
      "CHEMICAL & BACTERIOLOGICAL ANALYSIS REPORT OF WATER - FROM NABL OR GOVT. APPROVED LAB (IF MANUFACTURER)",
      "BSC DEGREE CERTIRICATE+MARKSHEET+PHOTO ID PROOF OF B.SC. DEGREE HOLDER (BSC IN FOOD TECHNOLOGY, DAIRY TECHNOLOGY, CHEMISTRY, MICRO BIOLOGY)",
    ],
    pvtOptions: [
      "LIST OF FOOD ITEMS LIST",
      "IMPORT EXPORT CERTIFICATE (IEC CODE)",
      "PARTNERSHIP DEED-IN CIN/MOA- OF COMPANY.",
      "PHOTO ID PROOF (WITH ADDRESS) OF (PARTNERS/DIRECTORS).",
      "PASSPORT SIZED PHOTOGRAPHS-2 (ALL PARTNERS/DIRECTORS)",
      "BLANK LETTERHEADS-25 NOS. (WITH SIGN & STAMP & A4 SIZE)",
      "PHOTOGRAPHS OF UNIT IN SOFT COPY.",
      "PROOF OF BUSINESS PREMISES- OWNERSHIP (DOCUMENT/ELECTRICITY BILL/RENT AGREEMENT)",
      "LIST OF PLANT & MACHINERY-WITH HORSE POWER AND NO. OF MACHINES (IF MANUFACTURER)",
      "GROUND PLAN OF THE UNIT (IF MANUFACTURER)",
      "CHEMICAL & BACTERIOLOGICAL ANALYSIS REPORT OF WATER - FROM NABL OR GOVT. APPROVED LAB (IF MANUFACTURER)",
      "LIST OF LABORATORY EQUIPMENT (IF MANUFACTURER)",
      "BSC DEGREE CERTIRICATE+MARKSHEET+PHOTO ID PROOF OF B.SC. DEGREE HOLDER (BSC IN FOOD TECHNOLOGY, DAIRY TECHNOLOGY, CHEMISTRY, MICRO BIOLOGY)",
    ],
    isMultipleEntity: true,
  },
  {
    service: "CHECKLIST FOR GEM (E-MARKET PLACE)",
    soleOptions: [
      "BUSINESS NAME",
      "BUSINESS ADDRESS",
      "NATURE OF BUSINESS",
      "PROPRIETOR'S PAN CARD",
      "PROPRIETOR'S AADHAAR CARD",
      "BUSINESS E-MAIL ID & MOBILE NUMBER",
      "CANCELLED CHEQUE LEAF WITH THE FIRM NAME PRINTED (IF AVAILABLE)",
    ],
    pvtOptions: [
      "CIN NUMBER",
      "BUSINESS NAME",
      "BUSINESS ADDRESS",
      "NATURE OF BUSINESS",
      "COMPANY PAN CARD",
      "DIRECTOR’S AADHAAR CARD",
      "BUSINESS COMMENCEMENT DATE",
      "DIRECTOR’S PASSPORT SIZE PHOTO",
      "BUSINESS E-MAIL ID & MOBILE NUMBER",
      "CANCELLED CHEQUE LEAF WITH THE FIRM NAME PRINTED (IF AVAILABLE)",
    ],
    isMultipleEntity: true,
  },
  {
    service: "CHECKLIST FOR GST",
    soleOptions: [
      "BUSINESS NAME",
      "BUSINESS ADDRESS",
      "NATURE OF BUSINESS",
      "PROPRIETOR'S PAN CARD",
      "PROPRIETOR'S AADHAAR CARD",
      "BUSINESS COMMENCEMENT DATE",
      "PROPRIETOR'S PASSPORT SIZE PHOTO",
      "BUSINESS E-MAIL ID & 5. BUSINESS MOBILE NUMBER",
      "CANCELLED CHEQUE LEAF WITH THE FIRM NAME PRINTED (IF AVAILABLE)",
      "PREFERRED ACTIVITY: MERCHANT EXPORTER OR SERVICE PROVIDER OR MERCHANT CUM SERVICE PROVIDER (KINDLY INDICATE THE APPROPRIATE ONE).",
      "BUSINESS ADDRESS PROOF (IF RENTED) - RENTAL AGREEMENT OR LEASE AGREEMENT ALONG WITH LATEST ELECTRICITY BILL & EB CARD XEROX (IF OWNED) - MUNICIPAL KHATA COPY OR SALE DEED OR PROPERTY TAX RECEIPT (LATEST) ALONG WITH LATEST ELECTRICITY BILL.",
    ],
    pvtOptions: [
      "DIN NUMBER",
      "CIN NUMBER",
      "BUSINESS NAME",
      "BUSINESS ADDRESS",
      "NATURE OF BUSINESS",
      "COMPANY PAN CARD",
      "DIRECTOR’S AADHAAR CARD",
      "BUSINESS COMMENCEMENT DATE",
      "DIRECTOR’S PASSPORT SIZE PHOTO",
      "BUSINESS E-MAIL ID & MOBILE NUMBER",
      "CANCELLED CHEQUE LEAF WITH THE FIRM NAME PRINTED (IF AVAILABLE)",
      "PREFERRED ACTIVITY: MERCHANT EXPORTER OR SERVICE PROVIDER OR MERCHANT CUM SERVICE PROVIDER (KINDLY INDICATE THE APPROPRIATE ONE).",
      "BUSINESS ADDRESS PROOF (IF RENTED) - RENTAL AGREEMENT OR LEASE AGREEMENT ALONG WITH LATEST ELECTRICITY BILL & EB CARD XEROX (IF OWNED) - MUNICIPAL KHATA COPY OR SALE DEED OR PROPERTY TAX RECEIPT (LATEST) ALONG WITH LATEST ELECTRICITY BILL.",
    ],
    isMultipleEntity: true,
  },
  {
    service: "CHECKLIST FOR IEC CODE",
    soleOptions: [
      "PAN CARD",
      "AADHAR CARD",
      "LEGAL DOCUMENTS (MSME/GST/TRADE LICENSE)",
      "PHONE NUMBER AND EMAIL ID",
      "BANK ACCOUNT STATEMENT/CANCEL CHEQUE IN THE NAME OF THE ORGANIZATION",
    ],
    pvtOptions: [
      "PAN CARD OF BUSINESS ENTITY.",
      "CERTIFICATE OF INCORPORATION",
      "PHONE NUMBER AND EMAIL ID",
      "AOA AND MOA IN THE CASE OF COMPANY OR LLP AGREEMENT IN THE CASE OF LLP OR PARTNERSHIP DEED IN THE CASE OF PARTNERSHIP FIRM.",
      "BANK ACCOUNT STATEMENT/CANCEL CHEQUE IN THE NAME OF THE ORGANIZATION",
      "LIST OF PARTNERS OR DIRECTORS AADHAR CARD, PAN CARD & NUMBER",
    ],
    isMultipleEntity: true,
  },
  {
    service: "Document Required for Certification (For Domestic IAF)",
    soleOptions: [
      "Company Registration Copy",
      "Sales Invoice 2copy",
      "Purchase Invoice 2copy",
      "Owner I'D Proof (Passport, Driving License, Other Govt License)",
      "Address Proof (Rent Agreement, Electricity Bill)",
      "Organization Flow Chart",
      "Process Flow Chart",
      "Organization Picture",
      "Audit Application Form Sign & Stamp",
    ],
    pvtOptions: [
      "Company Registration Copy",
      "Sales Invoice 2copy",
      "Purchase Invoice 2copy",
      "Owner I'D Proof (Passport, Driving License, Other Govt License)",
      "Address Proof (Rent Agreement, Electricity Bill)",
      "Organization Flow Chart",
      "Process Flow Chart",
      "Organization Picture",
      "Audit Application Form Sign & Stamp",
    ],
  },
  {
    service: "Document Required for Certification (For Domestic Non -IAF)",
    soleOptions: [
      "Company Registration Copy",
      "Sales Invoice 2copy",
      "Purchase Invoice 2copy",
      "Owner I'D Proof (Passport, Driving License, Other Govt License)",
      "Address Proof (Rent Agreement, Electricity Bill)",
      "Organization Picture",
    ],
    pvtOptions: [
      "Company Registration Copy",
      "Sales Invoice 2copy",
      "Purchase Invoice 2copy",
      "Owner I'D Proof (Passport, Driving License, Other Govt License)",
      "Address Proof (Rent Agreement, Electricity Bill)",
      "Organization Picture",
    ],
  },
  {
    service: "Document Required for Certification (for International)",
    soleOptions: [
      "Company Registration Copy (CR / Trade Licence /Others Registration)",
      "Sales Invoice 2copy",
      "Purchase Invoice 2copy",
      "Owner I'D Proof (Passport, Driving License, Other Govt License)",
      "Address Proof (Rent Agreement, Electricity Bill)",
      "Organization Flow Chart",
      "Process Flow Chart",
      "Scope of Work/Services in letter head",
      "Company Profile / Website (if available)",
      "Organization Picture",
      "Audit Application Form Sign & Stamp",
    ],
    pvtOptions: [
      "Company Registration Copy (CR / Trade Licence /Others Registration)",
      "Sales Invoice 2copy",
      "Purchase Invoice 2copy",
      "Owner I'D Proof (Passport, Driving License, Other Govt License)",
      "Address Proof (Rent Agreement, Electricity Bill)",
      "Organization Flow Chart",
      "Process Flow Chart",
      "Scope of Work/Services in letter head",
      "Company Profile / Website (if available)",
      "Organization Picture",
      "Audit Application Form Sign & Stamp",
    ],
  },
  {
    service: "CHECKLIST FOR LIMITED LIABILITY COMPANY",
    soleOptions: [
      "PANCARD",
      "2 PHOTOS",
      "AADHAR CARD",
      "NOC FROM OWNER",
      "(2) PROPOSED NAME",
      "ID POOF OF MEMBERS",
      "OBJECT OF THE COMPANY",
      "BANK STATEMENT OR LIGHT BILL",
      "CAPITAL CONTRIBUTED BY EACH PERSON",
      "DIN NO. OF ALL THE DIRECTORS (IF ANY).",
      "SUBSCRIBER TO THE MEMORANDUM AND ARTICLE IF DIFFERENT.",
      "BUSINESS ADDRESS PROOF (ELECTRIC BILL / RENT AGREEMENT)",
    ],
    pvtOptions: [
      "PANCARD",
      "2 PHOTOS",
      "AADHAR CARD",
      "NOC FROM OWNER",
      "(2) PROPOSED NAME",
      "ID POOF OF MEMBERS",
      "OBJECT OF THE COMPANY",
      "BANK STATEMENT OR LIGHT BILL",
      "CAPITAL CONTRIBUTED BY EACH PERSON",
      "DIN NO. OF ALL THE DIRECTORS (IF ANY).",
      "SUBSCRIBER TO THE MEMORANDUM AND ARTICLE IF DIFFERENT.",
      "BUSINESS ADDRESS PROOF (ELECTRIC BILL / RENT AGREEMENT)",
    ],
  },
  {
    service: "CHECKLIST FOR MSME (UDYAM AADHAR)",
    soleOptions: [
      "AADHAR CARD",
      "PAN CARD",
      "OFFICE ADDRESS",
      "MOBILE NO",
      "EMAIL ID",
      "INVESTMENT",
      "CANCELLED CHEQUE",
      "NO. OF EMPLOYEE (M/F)",
      "DESCRIPTION OF THE BUSINESS:",
      "TRADE DESCRIPTION: MANUFACTURER / TRADER / SERVICE PROVIDER",
      "COMPANY TYPE: PROPRIETOR / PVT. LTD. / LTD. / LLP/ PARTNERSHIP/ TRUST / KARTA -HUF/ SOCIETY/ GOV. DEPT. & STATUTORY ORG.",
    ],
    pvtOptions: [
      "AADHAR CARD",
      "COMPANY PAN CARD",
      "OFFICE ADDRESS",
      "MOBILE NO",
      "EMAIL ID",
      "INVESTMENT",
      "CANCELLED CHEQUE",
      "NO. OF EMPLOYEE (M/F)",
      "DESCRIPTION OF THE BUSINESS:",
      "TRADE DESCRIPTION: MANUFACTURER / TRADER / SERVICE PROVIDER",
      "COMPANY TYPE: PROPRIETOR / PVT. LTD. / LTD. / LLP/ PARTNERSHIP/ TRUST / KARTA -HUF/ SOCIETY/ GOV. DEPT. & STATUTORY ORG.",
    ],
    isMultipleEntity: true,
  },
  {
    service: "CHECKLIST FOR PRIVATE LIMITED COMPANY",
    soleOptions: [
      "PANCARD",
      "2 PHOTOS",
      "AADHAR CARD",
      "NOC FROM OWNER",
      "(2) PROPOSED NAME",
      "ID POOF OF MEMBERS",
      "OBJECT OF THE COMPANY",
      "BANK STATEMENT OR LIGHT BILL",
      "CAPITAL CONTRIBUTED BY EACH PERSON",
      "DIN NO. OF ALL THE DIRECTORS (IF ANY).",
      "SUBSCRIBER TO THE MEMORANDUM AND ARTICLE IF DIFFERENT.",
      "BUSINESS ADDRESS PROOF (ELECTRIC BILL / RENT AGREEMENT)",
    ],
    pvtOptions: [
      "PANCARD",
      "2 PHOTOS",
      "AADHAR CARD",
      "NOC FROM OWNER",
      "(2) PROPOSED NAME",
      "ID POOF OF MEMBERS",
      "OBJECT OF THE COMPANY",
      "BANK STATEMENT OR LIGHT BILL",
      "CAPITAL CONTRIBUTED BY EACH PERSON",
      "DIN NO. OF ALL THE DIRECTORS (IF ANY).",
      "SUBSCRIBER TO THE MEMORANDUM AND ARTICLE IF DIFFERENT.",
      "BUSINESS ADDRESS PROOF (ELECTRIC BILL / RENT AGREEMENT)",
    ],
  },
  {
    service: "CHECKLIST FOR SECTION-8",
    soleOptions: [
      "PANCARD",
      "AADHAR CARD",
      "NOC FROM OWNER",
      "(2) PROPOSED NAME",
      "ID POOF OF MEMBERS",
      "OBJECT OF THE COMPANY",
      "2 PHOTOS OF EACH MEMBER",
      "BANK STATEMENT OR LIGHT BILL",
      "CAPITAL CONTRIBUTED BY EACH PERSON.",
      "SUBSCRIBER TO THE MEMORANDUM AND ARTICLE IF DIFFERENT.",
      "DIN NO. OF ALL THE DIRECTORS (IF ANY).",
      "BUSINESS ADDRESS PROOF (ELECTRIC BILL / RENT AGREEMENT)",
    ],
    pvtOptions: [
      "PANCARD",
      "AADHAR CARD",
      "NOC FROM OWNER",
      "(2) PROPOSED NAME",
      "ID POOF OF MEMBERS",
      "OBJECT OF THE COMPANY",
      "2 PHOTOS OF EACH MEMBER",
      "BANK STATEMENT OR LIGHT BILL",
      "CAPITAL CONTRIBUTED BY EACH PERSON.",
      "SUBSCRIBER TO THE MEMORANDUM AND ARTICLE IF DIFFERENT.",
      "DIN NO. OF ALL THE DIRECTORS (IF ANY).",
      "BUSINESS ADDRESS PROOF (ELECTRIC BILL / RENT AGREEMENT)",
    ],
  },
  {
    service:
      "CHECKLIST FOR SPICE BOARD REGISTRATION AS EXPORTER OF SPICES (CRES)",
    soleOptions: [
      "SELF-ATTESTED COPY OF PAN CARD OF THE APPLICANT",
      "ALSO, A SELF-CERTIFIED COPY OF GST REGISTRATION CERTIFICATE",
      "SELF-ATTESTED COPY OF THE IMPORT-EXPORT CODE CERTIFICATE",
      "A PASSPORT SIZE PHOTO OF THE CEO OR DESIGNATED OFFICER OF YOUR FIRM",
      "APPLICATION IN THE PRESCRIBED FORM I.E., FORM-I UNDER SECTION 12 OF THE SPICES BOARD {REGISTRATION OF EXPORTERS} REGULATION, 1989",
      "LEGAL DOCUMENTS (MSME/ TRADE LICENSE)",
      "IN CASE THE APPLICANT IS AN EXPORTER OF MANUFACTURED SPICES PRODUCTS, THERE IS A NEED TO SUBMIT A SELF-ATTESTED CERTIFICATE ISSUED BY THE DIRECTORATE OF INDUSTRIES",
    ],
    pvtOptions: [
      "DIRECTOR COPY OF PAN CARD OF THE APPLICANT",
      "ALSO, A SELF-CERTIFIED COPY OF GST REGISTRATION CERTIFICATE",
      "SELF-ATTESTED COPY OF THE IMPORT-EXPORT CODE CERTIFICATE",
      "A PASSPORT SIZE PHOTO OF THE CEO OR DESIGNATED OFFICER OF YOUR FIRM",
      "APPLICATION IN THE PRESCRIBED FORM I.E., FORM-I UNDER SECTION 12 OF THE SPICES BOARD {REGISTRATION OF EXPORTERS} REGULATION, 1989",
      "SELF-CERTIFIED COPIES OF PARTNERSHIP DEED OR MEMORANDUM OF ASSOCIATION {MOA} AND ARTICLE OF ASSOCIATION {AOA}, AS PER THE REQUIREMENT OF THE CASE",
      "IN CASE THE APPLICANT IS AN EXPORTER OF MANUFACTURED SPICES PRODUCTS, THERE IS A NEED TO SUBMIT A SELF-ATTESTED CERTIFICATE ISSUED BY THE DIRECTORATE OF INDUSTRIES",
    ],
    isMultipleEntity: true,
  },
  {
    service: "CHECKLIST FOR START UP INDIA",
    soleOptions: [
      "MEMORANDUM OF ASSOCIATION OF THE COMPANY/LLP/PARTNERSHIP FIRM",
      "CERTIFICATE OF INCORPORATION OF THE COMPANY/LLP/PARTNERSHIP FIRM",
      "PAN CARD OF THE COMPANY/LLP/PARTNERSHIP FIRM",
      "ELABORATE YOUR BUSINESS",
      "WHAT PROBLEM DOES YOUR STARTUP SOLVES?",
      "HOW YOUR STARTUP DOES PROPOSE TO SOLVE THE PROBLEM?",
      "WHAT IS THE UNIQUENESS OF YOUR BUSINESS?",
      "HOW DOES YOUR STARTUP GENERATE REVENUE?",
      "INNOVATION, IDEA, IMPROVEMENT, SCALABILITY OF PRODUCT OR SERVICE?",
      "ID PROOF",
      "CONTACT AND EMAIL ID",
      "NUMBER OF EMPLOYEES:",
      "DETAILS OF THE DIRECTORS/PARTNERS",
      "WEBSITE (IF ANY) OF THE COMPANY/LLP/PARTNERSHIP FIRM",
      "PITCH DECK (IF ANY) OF THE COMPANY/LLP/PARTNERSHIP FIRM",
    ],
    pvtOptions: [
      "MEMORANDUM OF ASSOCIATION OF THE COMPANY/LLP/PARTNERSHIP FIRM",
      "CERTIFICATE OF INCORPORATION OF THE COMPANY/LLP/PARTNERSHIP FIRM",
      "PAN CARD OF THE COMPANY/LLP/PARTNERSHIP FIRM",
      "ELABORATE YOUR BUSINESS",
      "WHAT PROBLEM DOES YOUR STARTUP SOLVES?",
      "HOW YOUR STARTUP DOES PROPOSE TO SOLVE THE PROBLEM?",
      "WHAT IS THE UNIQUENESS OF YOUR BUSINESS?",
      "HOW DOES YOUR STARTUP GENERATE REVENUE?",
      "INNOVATION, IDEA, IMPROVEMENT, SCALABILITY OF PRODUCT OR SERVICE?",
      "ID PROOF",
      "CONTACT AND EMAIL ID",
      "NUMBER OF EMPLOYEES:",
      "DETAILS OF THE DIRECTORS/PARTNERS",
      "WEBSITE (IF ANY) OF THE COMPANY/LLP/PARTNERSHIP FIRM",
      "PITCH DECK (IF ANY) OF THE COMPANY/LLP/PARTNERSHIP FIRM",
    ],
  },
  {
    service: "CHECKLIST FOR TRADE LICENSE",
    soleOptions: [
      "PAN CARD",
      "AADHAR CARD",
      "BUSINESS AREA",
      "BUSINESS DESCRIPTION",
      "BUSINESS ADDRESS PROOF",
      "PHONE NUMBER AND EMAIL ID",
    ],
    pvtOptions: [
      "BUSINESS AREA",
      "BUSINESS DESCRIPTION",
      "PHONE NUMBER AND EMAIL ID",
      "PAN CARD OF BUSINESS ENTITY.",
      "CERTIFICATE OF INCORPORATION",
      "LIST OF PARTNERS OR DIRECTORS AADHAR CARD, PAN CARD & NUMBER",
      "AOA AND MOA IN THE CASE OF COMPANY OR LLP AGREEMENT IN THE CASE OF LLP OR PARTNERSHIP DEED IN THE CASE OF PARTNERSHIP FIRM.",
    ],
    isMultipleEntity: true,
  },
];
